// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBo6FD9EDBBk4U9gqyAcAcHUbP9hk7rs',
    appId: '1:561883177042:web:932b6e3551302da2d07f8b',
    messagingSenderId: '561883177042',
    projectId: 'fir-prtice',
    authDomain: 'fir-prtice.firebaseapp.com',
    storageBucket: 'fir-prtice.appspot.com',
    measurementId: 'G-JMYYS8E7X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUx9IRe-AlRnLs8VZ9jIiW09B_gqkbkQ',
    appId: '1:561883177042:android:0c3ba33efbfc6c3dd07f8b',
    messagingSenderId: '561883177042',
    projectId: 'fir-prtice',
    storageBucket: 'fir-prtice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAdqeykUGpASaGUg15UAZn9nk-dt62kQ',
    appId: '1:561883177042:ios:b7efcc50d38d0e8ed07f8b',
    messagingSenderId: '561883177042',
    projectId: 'fir-prtice',
    storageBucket: 'fir-prtice.appspot.com',
    iosBundleId: 'com.example.firebasePratice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAdqeykUGpASaGUg15UAZn9nk-dt62kQ',
    appId: '1:561883177042:ios:b7efcc50d38d0e8ed07f8b',
    messagingSenderId: '561883177042',
    projectId: 'fir-prtice',
    storageBucket: 'fir-prtice.appspot.com',
    iosBundleId: 'com.example.firebasePratice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtBo6FD9EDBBk4U9gqyAcAcHUbP9hk7rs',
    appId: '1:561883177042:web:0720d882395eb8c3d07f8b',
    messagingSenderId: '561883177042',
    projectId: 'fir-prtice',
    authDomain: 'fir-prtice.firebaseapp.com',
    storageBucket: 'fir-prtice.appspot.com',
    measurementId: 'G-STJVGMR7FX',
  );
}
